apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2 
  zones: us-east-2b
  iopsPerGB: "10"
reclaimPolicy: Delete
allowVolumeExpansion: false


