apiVersion: v1
kind: Service
metadata:
  name: {{.Values.deployment.name}}
spec:
  selector:
    app: {{.Values.deployment.name}}
  type: {{.Values.service.type}}
  ports:
    - nodePort: {{.Values.service.nodePort}}
      port: 6000
      targetPort: {{.Values.service.targetPort}}